eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: service

  #################redis基础配置#################
  redis:
    database: 5
    host: 47.106.148.133
    password: 123456
    port: 6379
  # 连接超时时间 单位 ms（毫秒）
    timeout: 3000
    pool:
      # 连接池中的最大空闲连接，默认值也是8。
      max-idle: 500
      #连接池中的最小空闲连接，默认值也是0。
      min-idle: 50
      # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-active: 2000
      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
      max-wait: 1000
    session:
          store-type: none
#################redis哨兵设置#################
#    sentinel:
#      master: master8026
#      redis-sentinel的配置地址和端口
#      nodes: 10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378
